lowercase emails before comparing with credential email
accredible/accredible-certificates pull request #19
Opened 2022-03-29 08:11 UTC by octaviorequena

The emails from the credentials are always in lowercase.

This PR ensure that all emails are lowercase when comparing to fix an issue
where users with uppercase emails can't find their credential.

2022-03-29 12:33 UTC, kei178 requested changes
@octaviorequena - I think the problem has not been fixed. I manually changed the user email to have an uppercase letter, but the SSO link was not displayed as shown in the attached images below:

#### Before updating

<img width="1440" alt="Screen Shot 2022-03-29 at 21 25 18" src="https://user-images.githubusercontent.com/20009662/160611449-4d2fc1e6-9842-4913-b9e3-946f9608e41e.png">

#### After updating

<img width="1440" alt="Screen Shot 2022-03-29 at 21 27 45" src="https://user-images.githubusercontent.com/20009662/160611492-497bee5d-14b7-424c-b628-9849b1fb600e.png">
 
I think we need to change the logic at users_list.php#L92:

https://github.com/accredible/accredible-certificates/blob/374a156c2ef616c4fade984f34c9a0eb1b3bc17f/users_list.php#L92

Could you take another look?

2022-03-30 08:34 UTC, octaviorequena commented
Hi @kei178 - You were right, I needed to update that file as the endpoint to get all_credentials is case sensitive.

Thanks to your change I have been able to install the plugin in localhost and check that it's working.

<img width="1624" alt="Screenshot 2022-03-30 at 10 32 54" src="https://user-images.githubusercontent.com/91325424/160788204-ea81b75f-2e5f-4e9a-9afb-3fd9d1a42f43.png">
<img width="1617" alt="Screenshot 2022-03-30 at 10 32 24" src="https://user-images.githubusercontent.com/91325424/160788211-25c9fcba-7284-42f6-82f3-afce992f7d5a.png">

2022-03-30 11:37 UTC, kei178 approved these changes
I confirmed these changes fix the issue on the credentials list page.

2022-03-30 11:37 UTC, kei178 commented on accredible-academy-theme.php
> +					if($certificate->recipient->email == strtolower( $user->user_email )){
I could not confirm if this method is still being used, but this change would be necessary to make it work with emails that include uppercases.

2022-03-30 11:37 UTC, kei178 commented on accredible_certificates.php
> +			  if($cert->recipient->email == $user_email){
I think `hasCertificate` is not used anywhere anymore so alternatively, we could completely remove this method.

2022-03-31 07:09 UTC, naveenbalachandar approved these changes

2022-03-31 07:13 UTC, merged